### ISSUE TITLE
Module not staying logged in to device

### ISSUE THREAD

**Issue by cpuguru07** [bitfocus/companion-module-magewell-proconvert-decoder#2]
When Instance has been active for a while, commands (specifically "Set NDI Channel") result in the error: MW_STATUS_NOT_LOGGED_IN in the Companion event log. From the NDI Decoder logs, I can see the sessions timing out after 30 minutes of inactivity.

This module should send some sort of command to keep the connection alive and/or monitor the logged in state and log in again (if necessary) before issuing the command to the device and/or observe the response from the device and re-login and try the command again.

Work-around is to Disable/Enable the Instance before issuing the command, but I have a LOT of buttons and this is a royal PITA. It also creates a TON of sessions on the NDI Decoder.

**Comment by alex-vyverman** [comment]
I can confirm this behavior, rendering the plugin useless for me unfortunately.
Is this project completely abandoned?

**Comment by alex-vyverman** [comment]
If one would periodically run this part:

> let cmd = `/mwapi?method=login&id=${username}&pass=${password_md5}`;
> 		self.getRest(cmd, {}).then(function(result) {
> 			// Success
> 			self.status(self.STATUS_OK);
> 			self.login_cookie = result.response['headers']['set-cookie'];

I think this would keep the cookie updated causing you to stay logged in, but it might be best to have this confirmed by someone who knows this better.

**Comment by alex-vyverman** [comment]
...or update the cookie before a command gets executed. But this could create potential delays.

**Comment by josephdadams** [comment]
I added a function to log it back in every 30 minutes. I just pushed that to the beta builds. Have a great day.

**Comment by alex-vyverman** [comment]
@josephdadams Unfortunately the new build results in an error:

> 22.03.14 15:07:34 instance(proconvert-decoder2): 10.32.206.198 : TypeError: Cannot read property 'length' of undefined
> 22.03.14 15:07:29 instance(proconvert-decoder2): 10.32.206.198 : ReferenceError: init_login is not defined

**Comment by josephdadams** [comment]
Thanks for testing. I pushed a bugfix for the second error. Not sure about the first error; if you still see that, let me know and I can take another look. It could be a result of a pull request submitted by another author.

**Comment by alex-vyverman** [comment]
Many thanks @josephdadams 
I'll try the bugfix asap, and report back

**Comment by alex-vyverman** [comment]
The bugfix has done it's job, and it seems fine now. Many thanks for your swift fix @josephdadams! 
In case the 30m re-login is not sufficient, I'll report back here. 

Have a wonderfull day!

**Comment by alex-vyverman** [comment]
Hello @josephdadams 
I've monitored the plugin for a full night, and unfortunately we get this error precisely every hour :

> TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"

Followed by this error when you try to execute a set command afterwards:

> 10.xxx.xxx.xxx : MW_STATUS_NOT_LOGGED_IN

Any chance you could take a look? Many thanks for your effort!

**Comment by josephdadams** [comment]
I suspect that the login is failing on subsequent requests, resulting in an undefined cookie variable. Unfortunately I don't have one of these to test with, so debugging will be difficult on this end.

**Comment by cpuguru07** [comment]
Can confirm the errors reported by @alex-vyverman, but it does appear that the SET commands are still working (the Decoder source changes and the feedback variables in Companion do get updated correctly). There might have been one button press that did NOT work (when the module re-authenticated), but it worked after that. So you're on the right track, @josephdadams 

Let us know how we can help continue troubleshooting/debugging.

**Comment by cpuguru07** [comment]
Yes - the first SET command after timeout results in:
`TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Cookie"`
The subsequent SET commands results in the following (but the command does work):
`MW_STATUS_NOT_LOGGED_IN`

**Comment by josephdadams** [comment]
I just pushed a fix which removes a lot of the areas where the login cookie was purposefully being set to `null` in the event of an error. I'll get this pushed to the beta builds and you guys can try it out. I don't know if it will help or not.

**Comment by cpuguru07** [comment]
New error on 1 out of 4 instances (on 4 separate devices). This instance now doesn't work at all (goes straight to Error state as soon as I Enable/Save the Instance settings).
Error in Companion log: `ReferenceError: data is not defined`
When I check the device's logs, it shows a successful login.
The other 3 instances seem to be working as expected.
I am willing to help further troubleshooting if you let me know exactly what you need.
I'm going to give things a chance to timeout and see what happens.

**Comment by josephdadams** [comment]
I pushed another fix. Keep me posted

**Comment by cpuguru07** [comment]
Now the modules are timing out and not logging in again at all. (Same issue/status as before @josephdadams started working on it earlier this week.)
Error: `MW_STATUS_NOT_LOGGED_IN`

**Comment by alex-vyverman** [comment]
I can test this Friday. Is there any way of increasing debugging in some way to try and figure this out?

If necessary, I could look into setting up an encoder in some remote shell for you @josephdadams. I understand doing this blindly is not very efficient.

**Comment by cpuguru07** [comment]
Correction - I'm not sure why it timed out that one time, but it hasn't done it since. Will keep an eye on it as we use it more.
@josephdadams - thanks for your hard work on this module!

**Comment by josephdadams** [comment]
I could at least add something that tracks that not logged in error and tries to reinitiate the login. I’ll try to do that sometime.

**Comment by josephdadams** [comment]
Ok, I pushed a fix that anytime the `MW_STATUS_NOT_LOGGED_IN ` error comes up, it will try to log in again. You'll then have to re run your action manually, but it should keep you from having to disable and enable the module.

**Comment by alex-vyverman** [comment]
Hi @josephdadams 
Apologies for the delay. I took some time to evaluate the module. The trick or (re-)logging in when MW_STATUS_NOT_LOGGED_IN pops up seems to be working.
I've had that situation yesterday, and while not 100% perfection, it does work as the user naturally tries again when it didn't work the first time.
Many many thanks for your help. Much appreciated 👍
