### ISSUE TITLE
Add controls other than NDI

### ISSUE THREAD

**Issue by arthurerb** [bitfocus/companion-module-magewell-proconvert-decoder#5]
The current version of this module only gives control over NDI stream selection. The [API calls available](https://www.magewell.com/api-docs/pro-convert-decoder-api/) have support for many other options.
Can we get other options like [set-channel](https://www.magewell.com/api-docs/pro-convert-decoder-api/source/set-channel.html) added to use inputs other than NDI?

**Comment by arthurerb** [comment]
Thanks to @josephdadams for adding so many extra controls to this module!

**Comment by josephdadams** [comment]
My pleasure @arthurerb
